#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

# Workspaces
bspc monitor -d 1 2 3 4 5

# Gaps
bspc config border_width         2
bspc config window_gap          12

# Layout Config
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# Colorscheme
bspc config focused_border_color "#C9CBFF"
bspc config active_border_color "#B5E8E0"
bspc config normal_border_color "#575268"
bspc config presel_border_color "#B5E8E0"
bspc config focused_locked_border_color "#FAE3B0"
bspc config normal_locked_border_color "#F8BD96"
bspc config urgent_border_color "#F28FAD"
bspc config focused_sticky_border_color "#ABE9B3"
bspc config active_sticky_border_color "#ABE9B3"

# Window Rules
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

# Applications
lxqt-policykit-agent &
dex --autostart&
picom --experimental-backends &
feh --randomize --bg-scale /home/stationuwu/Pictures/Wallpapers
nm-applet
dunst -conf ~/.config/dunst/dunstrc &
/home/stationuwu/.config/bspwm/launch_bars.sh
